Repository CamIsTrick/CIT_backend, pull requests merged in 2024-03, with the labels that each got.

#8 feat : UserSession 생성 및 IceCandidateListener 연결
  src/main/java/cit/camistrick/service/UserSession.java
Labels: :zap: enhancement

#12 Feature/#11 WebSocketHandler 기반 구현
  src/main/java/cit/camistrick/Action/KurentoAction.java
  src/main/java/cit/camistrick/config/KurentoConfig.java
  src/main/java/cit/camistrick/handler/KurentoActionResolver.java
  src/main/java/cit/camistrick/handler/WebSocketHandler.java
Labels: :zap: enhancement

#14 Feature/#13 Room, RoomManager, UserSessoin 관련 객체 생성
  src/main/java/cit/camistrick/KurentoHandler.java
  src/main/java/cit/camistrick/domain/Room.java
  src/main/java/cit/camistrick/domain/UserSession.java
  src/main/java/cit/camistrick/repository/MemoryUserSessionRepository.java
  src/main/java/cit/camistrick/repository/UserSessionRepository.java
  src/main/java/cit/camistrick/service/RoomManager.java
Labels: :zap: enhancement

#23 Feature/#15 UserSession 만들어주는 함수 생성
  src/main/java/cit/camistrick/action/KurentoAction.java
  src/main/java/cit/camistrick/action/RoomFollowerAction.java
  src/main/java/cit/camistrick/action/RoomLeaderAction.java
  src/main/java/cit/camistrick/domain/Room.java
  src/main/java/cit/camistrick/domain/UserSession.java
Labels: :zap: enhancement

#26 Feature/#25 existing participant 전달 구현 & room의 broadcast 수정
  src/main/java/cit/camistrick/action/RoomFollowerAction.java
  src/main/java/cit/camistrick/domain/Room.java
  src/main/java/cit/camistrick/domain/UserSession.java
Labels: :zap: enhancement

#28 #22 CI/CD 기능 추가 구현
  .github/workflows/deploy.yml
  Dockerfile_kurento
  Dockerfile_nginx
  Dockerfile_spring
  data/default.conf
  docker-compose.yml
  src/main/java/cit/camistrick/TestData.java
Labels: :zap: enhancement

#33 feat : 에러 발생시 ErrorResponse를 프론트에게 보내는 로직 구현
  src/main/java/cit/camistrick/action/ErrorAction.java
  src/main/java/cit/camistrick/config/KurentoConfig.java
  src/main/java/cit/camistrick/handler/KurentoActionResolver.java
  src/main/java/cit/camistrick/handler/WebSocketHandler.java
Labels: :zap: enhancement

#37 Feature/#35 HandleSdpOfferAction 구현
  src/main/java/cit/camistrick/action/HandleSdpOfferAction.java
  src/main/java/cit/camistrick/config/KurentoConfig.java
Labels: :zap: enhancement

#41 feat : IceCandidateAction 로직 구현 #34
  src/main/java/cit/camistrick/action/IceCandidateAction.java
  src/main/java/cit/camistrick/config/KurentoConfig.java
  src/main/java/cit/camistrick/dto/kurento/IceCandidateDto.java
  src/main/java/cit/camistrick/dto/kurento/KurentoDto.java
Labels: :zap: enhancement

#39 Feature/#24 ExitAction 구현
  src/main/java/cit/camistrick/action/ExitAction.java
  src/main/java/cit/camistrick/config/KurentoConfig.java
Labels: :zap: enhancement

#42 fix : 잘못된 코드 수정 / user id 부분
  src/main/java/cit/camistrick/action/RoomFollowerAction.java
  src/main/java/cit/camistrick/action/RoomLeaderAction.java
Labels: :no_entry_sign: invalid

#44 Feature/#43 fix : existingParticipant에서 본인 제거
  src/main/java/cit/camistrick/domain/Room.java
Labels: :no_entry_sign: invalid

#45 fix : 잘못된 인수 전달 exitAction / id -> sessionId
  src/main/java/cit/camistrick/action/ExitAction.java
Labels: :no_entry_sign: invalid

#47 fix : 방 입장시 이미 존재하는 사용자들을 리스트로 반환
  src/main/java/cit/camistrick/domain/Room.java
Labels: :no_entry_sign: invalid

#49 bug : 입장한 유저 세션이 너무 빨리 끊기는 문제 #48
  src/main/java/cit/camistrick/config/KurentoConfig.java
Labels: :lady_beetle: bug
